### ISSUE TITLE
Order replacement load cells for the bumpem system

### ISSUE THREAD

**Issue by moorepants** [mechmotum/housekeeping#12]
Marten broke one of the s shape load cells and we are using a replacement we had in the lab. We should order two more load cells to match the ones in the bumpem system (one for replacement and one for backup).

**Comment by pcvanderzalmtudelft** [comment]
A purchase request has been send to the secretary

**Comment by pcvanderzalmtudelft** [comment]
We first need to send a quote for the price to the company Bienfait, before purchasing the load cells. This has just been done.

**Comment by pcvanderzalmtudelft** [comment]
After the company didnt reply for a while I have called them and they have send me a quote, which I send to the secretary.
[OFF42400075.PDF](https://github.com/mechmotum/housekeeping/files/14345836/OFF42400075.PDF)

**Comment by pcvanderzalmtudelft** [comment]
The 2 load cells are ordered
