### ISSUE TITLE
Checkout list needs more pages, a review, and clean up

### ISSUE THREAD

**Issue by moorepants** [mechmotum/housekeeping#16]
We are out of checkout sheets in the lab. More need to be printed. We also need to review all the old sheets and see if anything is still borrowed. If not we can trash the old sheets. Track down any missing items or move it to a new sheet.

@pcvanderzalmtudelft I mentioned this to you in passing. Can you put this on your TODO list?

**Comment by pcvanderzalmtudelft** [comment]
5 new checkout forms are in the lab and the template is in the drive

**Comment by moorepants** [comment]
Gracias!
